#!/usr/bin/python3

import argparse
import json
import re
import requests

AUTH_PATH = 'auth'
KEY_PATH = 'key'

AUTH_TOKEN = ''

class APIError(Exception):
    def __init__(self, status):
        self.status = status

    def __str__(self):
        return "APIError: status={}".format(self.status)

def auth(args):
    try:
        with open(KEY_PATH) as f:
            auth_str = json.load(f)
            response = requests.post('https://api.thetvdb.com/login', json=auth_str)
            if response.status_code != 200:
                raise ApiError('POST /login {}'.format(response.status_code))
            with open(AUTH_PATH, 'w') as f:
                json.dump(response.json(), f)
    except IOError:
        print('Create a json file named {} in this directory with your apikey, userkey, and username.'.format(KEY_PATH))

def authenticated():
    global AUTH_TOKEN
    try:
        with open(AUTH_PATH) as f:
            AUTH_TOKEN = {"Authorization": 'Bearer ' + json.load(f)['token']}
        return True
    except:
        print('Please run annie-mays auth to first get a valid JWT token.')

def search(args):
    query = {'name': args.name}
    if authenticated():
        response = requests.get('https://api.thetvdb.com/search/series', params=query, headers=AUTH_TOKEN)
        if response.status_code == 404:
            raise APIError('No results found.')
        if response.status_code != 200:
            raise APIError('GET /search/series {}'.format(response.status_code))

        result = {}
        for series in response.json()['data']:
            result[series['id']] = {
                    'seriesName': series['seriesName'],
                    'aliases': series['aliases'],
                    'firstAired': series['firstAired'],
                    }

        print(json.dumps(result, sort_keys=True, indent=4, ensure_ascii=False))

def format(fmt, name, ep):
    result = []
    token = False

    for c in fmt:
        if token:
            if c == 'N':
                result.append(name)
            elif c == 's':
                result.append(str(ep['airedSeason']))
            elif c == 'e':
                e = ep['episodeNumber']
                if e < 10:
                    e = '0' + str(e)
                else:
                    e = str(e)
                result.append(e)
            elif c == 'n':
                result.append(ep['episodeName'])
            token = False
        elif c == '%':
            token = True
        else:
            result.append(c)

    return ''.join(result)

def validate(name):
    return re.sub(r'[\\/:*?"<>|]', '', name)

def fetch(id, season):
    response = requests.get('https://api.thetvdb.com/series/{}/episodes'.format(id), headers=AUTH_TOKEN)
    if response.status_code == 404:
        raise APIError('Series not found.')
    if response.status_code != 200:
        raise APIError('GET /series/{}/episodes {}'.format(id, response.status_code))

    result = []
    for ep in response.json()['data']:
        if season is -1 or season == ep['airedSeason']:
            sort_val = ep['absoluteNumber']
            if sort_val is None:
                sort_val = -123456 + ep['airedEpisodeNumber']
            result.append((sort_val,
                {
                    'airedSeason': ep['airedSeason'],
                    'episodeName': ep['episodeName'],
                    'episodeNumber': ep['airedEpisodeNumber'],
                })
            )
    result.sort(key=lambda e: e[0])
    return result

def name_episodes(id, name, fmt, valid, episodes):
    if not name:
        name = requests.get('https://api.thetvdb.com/series/{}'.format(id), headers=AUTH_TOKEN).json()['data']['seriesName']

    result = []
    for ep in episodes:
        ep_name = format(fmt, name, ep[1])
        if valid:
            ep_name = validate(ep_name)
        result.append(ep_name)
    return result

def list_episodes(args):
    if authenticated():
        episodes = fetch(args.id, args.season)

        names = name_episodes(args.id, args.name, args.format, args.validate, episodes)
        [print(e) for e in names]

def main(argv=None):
    commands = {
        'auth': auth,
        'search': search,
        'list': list_episodes,
    }

    parser = argparse.ArgumentParser(description='Organizes and renames a directory of shows with data from TVDB.')
    subparsers = parser.add_subparsers(dest='command')
    subparsers.required = True

    parser_auth = subparsers.add_parser('auth', help='Creates an authentication token in this directory.')

    parser_search = subparsers.add_parser('search', help='Returns a list of series ids given a name.')
    parser_search.add_argument('name', type=str, help='name of a series')

    parser_list = subparsers.add_parser('list', help='Returns a list of all episodes for a given series.')
    parser_list.add_argument('id', type=int, help='series id')
    parser_list.add_argument('--name', type=str, default='', help='override series name')
    parser_list.add_argument('--season', type=int, default=-1, help='only show results for the specified season (default: all seasons)')
    parser_list.add_argument('--format', type=str, default='%N - %sx%e - %n', help='format for output list (default: %(default)s)')
    parser_list.add_argument('--validate', action='store_true', help='validates episode names to be valid filenames (default: false)')

    args = parser.parse_args(argv)
    return commands[args.command](args)

if __name__ == '__main__':
    main()
